defaults:
  - enjoy_pcgrl # This points to `EnjoyConfig` class in `config.py`
  - _self_

  # Why can't we override this on the command line?
  # - override hydra/sweeper: optuna

  - override hydra/launcher: drill_basic
  # - override hydra/launcher: drill_local
  # - override hydra/launcher: drill_slurm


render_mode: save_gif


hydra:
  verbose: true

  launcher:
    tasks_per_node: 1

    #FIXME: Can't set this to 1 or 2 even when only asking from 1 ("0") worker from ray...
    cpus_per_task: 1

    gpus_per_node: 1
    timeout_min: 60
    mem_gb: 30
    # Emails maybe?

  job:
    chdir: False
