defaults:
  - base_task

map_shape: [16, 16]
obs_window: [32, 32]

name: zelda2
problem: zelda2
weights:
  player: 3
  key: 3
  door: 3
  regions: 5
  enemies: 1
  nearest-enemy: 2
  path-length: 1
  